#!/bin/sh
if [ "$(id -u)" -ne 0 ]; then
  echo "Please run with sudo"
  exit 1
wget https://www.virtualhere.com/sites/default/files/usbserver/vhusbdarm64a72
chmod +x vhusbdarm64a72
mv vhusbdarm64a72 /usr/local/sbin
mkdir -p /usr/local/etc/virtualhere
if [ -d "/etc/systemd/system" ]; then
  cat << EOF > /etc/systemd/system/virtualhere.service
[Unit]
Description=VirtualHere Server
After=network.target
[Service]
Type=forking
ExecStart=/usr/local/sbin/vhusbdarm64a72 -b -c /usr/local/etc/virtualhere/config.ini
[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable virtualhere.service
  systemctl start virtualhere.service
fi
